# Generated by Django 5.1.15 on 2026-07-05 16:04

import django.db.models.deletion
import grading.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exercise_id', models.CharField(blank=True, max_length=64)),
                ('exercise_title', models.CharField(blank=True, max_length=200)),
                ('audio', models.FileField(upload_to=grading.models.submission_audio_path)),
                ('duration_seconds', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='studies.study')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GradingResult',
            fields=[
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='grade', serialize=False, to='grading.submission')),
                ('total_score', models.PositiveSmallIntegerField()),
                ('grade_label', models.CharField(max_length=4)),
                ('band', models.CharField(max_length=80)),
                ('pitch_score', models.FloatField()),
                ('rhythm_score', models.FloatField()),
                ('tempo_score', models.FloatField()),
                ('tone_score', models.FloatField()),
                ('completion_score', models.FloatField()),
                ('summary', models.TextField()),
                ('practice_tip', models.TextField()),
                ('analyzed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
