# Generated by Django 5.1.15 on 2026-07-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingresult',
            name='xp_awarded',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
