# Generated by Django 5.1.15 on 2026-07-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_gradingresult_xp_awarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingresult',
            name='note_extra',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gradingresult',
            name='note_grading',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gradingresult',
            name='note_results',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
