# Generated by Django 5.1.15 on 2026-07-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
