# Generated by Django 5.1.15 on 2026-07-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='streak_freezes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='xp_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
