# Generated by Django 5.1.15 on 2026-07-27 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('surface', models.CharField(choices=[('onboarding', 'Onboarding')], default='onboarding', max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('hypothesis', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('stopped', 'Stopped')], default='draft', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('surface',), name='features_one_running_experiment_per_surface')],
            },
        ),
        migrations.CreateModel(
            name='OnboardingVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='features_one_default_variant')],
            },
        ),
        migrations.CreateModel(
            name='ExperimentArm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=32)),
                ('weight', models.PositiveSmallIntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arms', to='features.experiment')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arms', to='features.onboardingvariant')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='ExperimentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('arm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='features.experimentarm')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='features.experiment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['arm', 'assigned_at'], name='features_ex_arm_id_851f78_idx')],
                'constraints': [models.UniqueConstraint(fields=('experiment', 'user'), name='features_unique_assignment_per_user')],
            },
        ),
        migrations.CreateModel(
            name='OnboardingStepView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_key', models.SlugField(max_length=64)),
                ('step_key', models.CharField(choices=[('name', 'name'), ('instrument', 'instrument'), ('experience', 'experience'), ('goal', 'goal'), ('practice', 'practice'), ('clarke', 'clarke')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step_views', to='features.experimentarm')),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step_views', to='features.experiment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_step_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'variant_key', 'step_key'), name='features_unique_step_view')],
            },
        ),
        migrations.AddConstraint(
            model_name='experimentarm',
            constraint=models.UniqueConstraint(fields=('experiment', 'key'), name='features_unique_arm_key'),
        ),
    ]
