# Generated by Django 5.1.15 on 2026-07-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistsignup',
            name='subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
