# Generated by Django 5.1.15 on 2026-07-26 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_google_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(blank=True, choices=[('trumpet', 'Trumpet'), ('cornet', 'Cornet'), ('flugelhorn', 'Flugelhorn'), ('piccolo-trumpet', 'Piccolo Trumpet'), ('french-horn', 'French Horn'), ('mellophone', 'Mellophone'), ('alto-horn', 'Alto / Tenor Horn'), ('baritone-treble', 'Baritone Horn (treble clef)'), ('euphonium-treble', 'Euphonium (treble clef)'), ('trombone', 'Trombone'), ('bass-trombone', 'Bass Trombone'), ('tuba', 'Tuba')], max_length=32)),
                ('experience_level', models.CharField(blank=True, choices=[('under_1', 'Less than a year'), ('y1_3', '1–3 years'), ('y3_7', '3–7 years'), ('over_7', '7+ years')], max_length=16)),
                ('primary_goal', models.CharField(blank=True, choices=[('tone', 'Better tone and control'), ('range', 'Extend my range'), ('endurance', 'Build endurance'), ('technique', 'Faster, cleaner technique'), ('consistency', 'Practice consistently'), ('audition', 'Prepare for an audition')], max_length=16)),
                ('practice_days_goal', models.PositiveSmallIntegerField(default=5)),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('reminder_enabled', models.BooleanField(default=False)),
                ('clarke_start_section', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user preferences',
            },
        ),
    ]
